export const helpText = [
  'Piclaw Pi Agent',
  '',
  'Commands:',
  '/remember global <text>',
  '/remember server <text>',
  '/memory - show memory',
  '/forget - clear short memory',
  '/status - bot status',
  '/mode - show current mode',
  '/model - choose Pi model',
  '/mode agent - full access',
  '/mode ask - read-only',
  '/reload - restart bot and load new code/config',
  '/cancel - cancel active task',
  'Voice message - transcribe with Whisper and run as task',
  '/server-status',
  '/server-services',
  '/server-logs <name>',
  '/server-restart <service>',
].join('\n');
