export const helpText = [
  'Piclaw Pi Agent',
  '',
  'Commands:',
  '/remember <text>',
  '/forget - clear saved long memory',
  '/memory - show long memory and session compact memory',
  '/usage - show estimated context usage',
  '/new - start fresh context',
  '/status - bot status',
  '/skills - show available skills',
  '/mode - show current mode',
  '/model - choose Pi model',
  '/login - connect LLM auth',
  '/logout - remove LLM auth',
  '/auth-status - show LLM auth status',
  '/auth-list - list auth providers',
  '/cancel-auth - cancel pending auth',
  '/mode agent - full access',
  '/mode ask - read-only',
  '/reload - restart bot and load new code/config',
  '/cancel - cancel active task',
  'Voice message - transcribe with Whisper and run as task',
  '/server-status',
  '/server-services',
  '/server-logs <name>',
  '/server-restart <service>',
].join('\n');
